server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:tweeterDB
    username: tweeter
    password: tweeter2023
  jpa:
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2

