server:
  port: 8080

spring:
  datasource:
#    url: jdbc:h2:mem:tweeterDB
    url: jdbc:h2:file:~/employees;AUTO_SERVER=true
    username: tweeter
    password: tweeter2023
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
  thymeleaf:
    check-template-location: false
    defer-datasource-initialization: true
    sql:
      init:
        mode: always
  h2:
    console:
      enabled: true
      path: /h2
  main:
    banner-mode: off

  logging:
    level:
      root:ERROR
      org:info



