server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://isilo.db.elephantsql.com/yofcgaph
    username: yofcgaph
    password: XzJChZAfOg7ew1UcwKSEO5K6yo6xTtPb
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 0
  jpa:
    generate-ddl: true
    show-sql: true
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
  main:
    banner-mode: off
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 429648578915-3m7p1im834dvg26q30gvbvb940adac83.apps.googleusercontent.com
            client-secret: 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

logging:
  level:
    root: info
    org: info