jdk: openjdk17
addons:
  sonarcloud:
    organization: "fp4socialnetwork"
    token:
      secure: "506f185a3ff3043be69834b4b93a168e491ec88a"

script:
  - mvn -f social_network_api/ clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AlexKhmarenko_FP4SocialNetwork
  - mvn -f social_network_api/ clean test jacoco:report coveralls:report