sudo: false
install: true

language: java

addons:
  sonarcloud:
    organization: "fp4socialnetwork"
    token:
      secure: "f81a82d401e44dc1c38e0ea337355a5ccb603671"
script:
  - sonar-scanner

after_success:
  - mvn -e -fsocial_network_api/ clean test jacoco:report coveralls:report