sudo: false
install: true

language: java
jdk: openjdk17

addons:
  sonarcloud:
    organization: "fp4socialnetwork"
    token:
      secure: "07c060f7d0d90cc1bf1bba9412f1109351c268b2"
script:
  - mvn -e -fsocial_network_api/ clean test jacoco:report coveralls:report
  - sonar-scanner
