jdk: openjdk17
addons:
  sonarcloud:
    organization: "fp4socialnetwork"
    token:
      secure: "506f185a3ff3043be69834b4b93a168e491ec88a"

script:
  - mvn -f social_network_api/ clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=AlexKhmarenko_FP4SocialNetwork
  - mvn -f social_network_api/ clean test jacoco:report coveralls:report

jdk: openjdk17
addons:
  sonarcloud:
    organization: "step-project-final-1-twitter"
    token:
      secure: "SIWattrmvuVP0943ztY5GWrYKvmowKMOSEZm75h2Zb4rUao+ZrQ881syT/zBH4zV+NMgnEiUhCkFOhs7QoU3Myfukbe1cDBqDsyBi9o0UxerwdTZxkZzGWZckkJ8lottY3rPCpwuUGrLU1yJdzUBs7d7lq951yhofLj2V5QhqLRPIaLOAJKxImhEOSZUBf/98lb4KaLXwTCxX3sZs/08Oh1k5kxAujLWhhKzeURV4brNvwQn6dh4q7joo3LMWIwRXLnaR2SC3G/YGCMcQGeMjrd3lPn404+52Pl3RDs6zN6f3FFF7oBjwSvRVOavx9xWs+L/NptLEE0JBPoxLkLR9qvAqt89y9DwQVQB2tEXO2HonRobhGK3qy6cwlidk9lFLqPnfM8dsw82YP/81P8cEFKyny1fvFQoRf2pL6/Ay0KY/eo+wjX3inEoKD8snyvIkBp2BWpBf8/RQkp7/Bm0yMmtbUzLxUe/11u3quVTBDK9jn+SriUe/71Q64T4TVt5kz46Wd/4AE7YevGpzQ9Vr2aDCoZrNRYuoxWTuFhTL0jdqagX0jTSFlo6tYXL6zFqvMj+MV0uT4SkPsvrg4eXj5pZh72Sm0GT2vMu0sIMOtoifzhSjYTuxxvui61WGL1Ynhefmtz5WHL/VcZB6b2zEtTsey8INzOzWPKwXCWCKjQ=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=PavelBortnovskyi_Final_Step_Full_1
after_success:
  - mvn clean test jacoco:report coveralls:report
