sudo: false
install: true

language: java
jdk: openjdk17

addons:
  sonarcloud:
    organization: "fp4socialnetwork"
    token:
      secure: "05426a5e39ea1799bd7aeb6cf468366ff4120e94"
script:
  - mvn -e -fsocial_network_api/ clean test jacoco:report coveralls:report
  - sonar-scanner
