name: Coveralls

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coveralls:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#        with:
#          java-version: 17

      #      - name: Setup Python
      #        uses: actions/setup-python@v2
      #        with:
      #          python-version: 3.8
      #
      #      - name: Install dependencies
      #        run: |
      #          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          mvn -e -fsocial_network_api/ clean test jacoco:report coveralls:report
#      - name: Coveralls report
#        uses: coverallsapp/github-action@master
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}