name: Coveralls

on:
  push:
    branches:
      -main
  pull_request:
    branches:
      - main

jobs:
  test_and_report:
    name: Test and Report
    runs-on: ubuntu-latest

    steps:
      - name: Run Tests with Jacoco
        run: mvn -f social_network_api/ clean test jacoco:report coveralls:report